import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/atomics/navbar.module";
import ReduxProvider from "@/components/provider.module";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sumber Makmur - Toko Bangunan Jaman Now",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${montserrat.variable} antialiased bg-white text-black`}>
          <Navbar />
          {children}
        </body>
      </ReduxProvider>

    </html>
  );
}