#gunakan base image dari node js versi 20
FROM node:20

#set working directory di dalam container
WORKDIR /app

#copy file project
COPY package*.json ./
COPY tsconfig.json ./
COPY prisma ./prisma
COPY src ./src

#install dependencies
RUN npm install

#build typescript ke dalam javascript
RUN npm run build

#copy file .env
COPY .env .env

#jalankan perintah saat container start
CMD ["npm", "run", "start"]